jackwuersch/Expat-Unlocked

config/routes.rb
=> routes.rb root, user_documents, documents, profile

app/controllers/user_documents_controller.rb, app/views/user_documents/create.html.erb, app/views/user_documents/index.html.erb, app/views/user_documents/show.html.erb, app/views/user_documents/update.html.erb, config/routes.rb, test/controllers/user_documents_controller_test.rb
user_document controller setup
=> user doc controller setup

app/mailers/application_mailer.rb, app/mailers/user_mailer.rb, app/views/user_mailer/welcome.html.erb, test/mailers/previews/user_mailer_preview.rb, test/mailers/user_mailer_test.rb
Starting work on the email notifications. Will be testing basic setup after this push.
=> Setting up email notifications

Gemfile.lock, app/controllers/documents_controller.rb, app/models/document.rb, app/models/user_document.rb, app/views/documents/index.html.erb, app/views/documents/show.html.erb, db/migrate/20190304081845_create_documents.rb, db/schema.rb, db/seeds.rb
documents view index and show, change doc_name to jp_name
=> documents view index and show, change doc_name to jp_name

Gemfile, Gemfile.lock, app/controllers/user_documents_controller.rb, app/mailers/reminder_mailer.rb, app/models/email.rb, app/models/user.rb, app/models/user_document.rb, app/views/user_mailer/reminder.html.erb, app/views/user_mailer/welcome.html.erb, config/environments/development.rb, db/migrate/20190305024248_create_emails.rb, db/schema.rb, db/seeds.rb, test/mailers/previews/user_mailer_preview.rb, test/mailers/user_mailer_test.rb, test/models/email_test.rb
followed lectures and have a basic email notification framework installed and an email model created.
=> Basic email notification setup

db/migrate/20190305045113_add_admin_to_users.rb, db/schema.rb
Added admin boolean to user model
=> Admin added to the user model

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
nav-bar width problem and color resolved. Bootstrap!
=> nav-bar setup for mobile and website browswers

app/controllers/pages_controller.rb, app/views/pages/scan_info.html.erb, config/routes.rb
scan_info page and routes set-up
=> scan_info page and routes set-up

app/assets/stylesheets/components/_base.scss, app/assets/stylesheets/components/_document.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_user-card.scss, app/javascript/packs/application.js, app/views/shared/_navbar.html.erb, app/views/user_documents/index.html.erb
* Implemented an animation and bg change when scrolling for the navbar.
* Added small hovers on user and document cards. 
* Added logic for when a user has no name or picture on the user document page. 
* Still need to fix the layout of the items in the navbar
=> Navbar and other fixes

app/controllers/user_documents_controller.rb, app/services/vision_api.rb
* Fixed name change for pic detection due to schema change
=> Vision API Method Name Change

app/assets/stylesheets/components/_card.scss, app/views/pages/home.html.erb, db/schema.rb
turned section into a button on the landing page
=> turned section into a button on the landing page

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_profile.scss, app/controllers/profiles_controller.rb, app/views/profiles/show.html.erb
profile styling framework done
=> profile styling framework done

app/assets/stylesheets/components/_base.scss, app/controllers/user_documents_controller.rb, app/services/vision_api.rb, app/views/layouts/application.html.erb, app/views/user_documents/index.html.erb, db/schema.rb
* Created method and basic logic to extract yen and date from a bill.
* Created the method to add the data into the database.
=> Vision api date and yen detect

app/assets/stylesheets/components/_base.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_user-documents.scss, app/views/profiles/show.html.erb, app/views/user_documents/index.html.erb, app/views/user_documents/show.html.erb
user_documents show styling framework finished
=> user_documents show styling framework finished

app/controllers/profiles_controller.rb, app/views/profiles/show.html.erb
display all filter logic completed
=> display all filter logic completed

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_masonry.scss, app/controllers/profiles_controller.rb, app/controllers/user_documents_controller.rb, app/views/shared/_navbar.html.erb, app/views/user_documents/_bill-list.html.erb, app/views/user_documents/index.html.erb
small changes on a few files to get the filter working smoothly.
=> Filter feature

Gemfile.lock, app/policies/user_document_policy.rb, app/views/user_documents/index.html.erb
@user_documents now only show current_user user_documents.
=> scoping issue resolved

app/views/profiles/show.html.erb, app/views/user_documents/index.html.erb, app/views/user_documents/index.js
removed the filter button and drop down will now auto submit
=> User doc styling

app/assets/stylesheets/components/_user-card.scss, app/controllers/profiles_controller.rb, app/models/user_document.rb, app/views/profiles/_due-cards.html.erb, app/views/profiles/show.html.erb
* Methods will now get the average, highest, lowest for the current year.
=> User doc methods year

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_base.scss, app/assets/stylesheets/components/_navbar.scss, app/javascript/packs/application.js, app/views/pages/home.html.erb, app/views/profiles/_due-card.html.erb, app/views/profiles/_due-cards.html.erb, app/views/profiles/show.html.erb, app/views/shared/_navbar.html.erb, app/views/user_documents/pay.js.erb, app/views/user_documents/unpaid.js.erb
* Fixed the mobile design in the home page
* Worked on the navbar and reimplemented the js on click.
* Fixed the non working ajax for the paid to display the cards.
=> Mobile design

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_base.scss, app/views/user_documents/index.html.erb
user cards are satisfactory for today's pitch.
=> User docs cards

app/assets/stylesheets/components/_due-card.scss, app/views/profiles/_due-card.html.erb
profile bill card image size set at 200px
=> profile bill card image size set at 200px

app/controllers/application_controller.rb, app/controllers/users/registrations_controller.rb
=> redirect sign up and sign in to profile

app/assets/stylesheets/components/_filter.scss, app/controllers/profiles_controller.rb, app/models/user_document.rb
* Added stats for gas, electricity, and water.
=> Profile stats

app/javascript/packs/application.js, app/views/profiles/show.html.erb
* Added the missing stat to profile
* Change the toggle text
=> Profile stats js

app/assets/stylesheets/components/_base.scss, app/assets/stylesheets/components/_upcoming-card.scss, app/views/profiles/_bill-list.html.erb, app/views/profiles/_due-bills.html.erb, app/views/profiles/show.html.erb
* Added number with delimiters on profile yen amounts.
=> Sticky card bug

app/assets/stylesheets/components/_base.scss, app/views/user_documents/show.html.erb
conbini info is styled correctly.
=> Show page styling

app/controllers/user_documents_controller.rb, app/views/user_documents/index.html.erb
=> Filter placeholder

app/assets/stylesheets/components/_base.scss, app/assets/stylesheets/components/_profile-stats.scss, app/assets/stylesheets/components/_upcoming-card.scss, app/javascript/packs/application.js, app/views/profiles/_stats.html.erb, app/views/user_documents/show.html.erb
* Changed the profile stats icons and the header for the cards.
* Modified size of konbini icons
=> Profile layout changes

app/assets/stylesheets/components/_base.scss, app/assets/stylesheets/components/_card.scss, app/views/user_documents/index.html.erb, app/views/user_documents/show.html.erb
* Modified the header of the cards
=> fixed the header of the cards in the user docs index

app/javascript/packs/application.js, app/javascript/plugins/flatpickr.js, app/views/user_documents/show.html.erb
=> Calendar circle

app/assets/stylesheets/components/_profile.scss
* Profile looks better on mobile devices now
=> Mobile profile page
